version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.13.2
  codecov: codecov/codecov@3.2.5

workflows:
  build:
    jobs:
      - test-37:
          context:
            - docker
      - test-38:
          context:
            - docker
      - test-39:
          context:
            - docker
      - test-310:
          context:
            - docker
      - test-311:
          context:
            - docker

jobs:
  test-37: &test-template
    docker:
      - image: cimg/python:3.7.16
        auth:
          username: jpvantassel
          password: $DOCKER_PASS
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            virtualenv venv
            . venv/bin/activate
            mkdir test-results
      - run:
          name: Install numpy
          command: |
            . venv/bin/activate
            pip install numpy
      - run:
          name: Install sigpropy from source
          command: |
            . venv/bin/activate
            pip install git+ssh://git@github.com/jpvantassel/sigpropy.git
      - run:
          name: Install swprocess and dependencies
          command: |
            . venv/bin/activate
            pip install -e .[dev]
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd test
            coverage run --source=../swprocess -m unittest
      - run:
          name: Create coverage xml
          command: |
            . venv/bin/activate
            mv test/.coverage test-results
            cd test-results
            coverage xml -o cobertura.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload:
          file: test-results/cobertura.xml
      - coverage-reporter/send_report:
          coverage-reports: test-results/cobertura.xml
          project-token: $CODACY_PROJECT_TOKEN

  test-38:
    <<: *test-template
    docker:
      - image: cimg/python:3.8.16
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9.16
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10.10
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11.3
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

